### PR TITLE
Add note regarding unblocking the DLLs in readme

### PR DESCRIPTION
**Pull request by Karneades**

### CODE REVIEW

**Comment by EricZimmerman** [comment]
this is a non issue if the directions on the download page are followed

i.e. do not unzip with Windows

**Comment by Karneades** [comment]
FTR It happend today also with another ZIP download including DLLs and I used 7zip to extract, the DLLs were also blocked after unzip.

**Comment by EricZimmerman** [comment]
yea, dont use Windows to unzip, ever

**Comment by EricZimmerman** [comment]
i suppose, if 7z is being blocked, that Windows changed something, but i have not seen it do this myself

**Pull request merged**
