### PR TITLE
Update RECmd_Batch_MC.reb

### PR DESCRIPTION
**Pull request by karch4n6**
added trailing " \\* " to keypath for MS Office MRU plugin to generate output - (possibly unexpected behavior when plugin ends with wildcard + recursive: true?)

### CODE REVIEW

**Comment by EricZimmerman** [comment]
need more info on this, does your PR fix the issue? was there just a missing level of key paths or?

**Comment by karch4n6** [comment]
The PR does fix the issue - without it, no output for MS Office MRU is generated.  With the added trailing backslash + wildcard, output file is created.  Tested this on a live win10 machine and the dblake image.  The current keypath already ended with backslash + wildcard...so I was somewhat surprised that it did not seem to be truly recursive / keep going into the next subkey.  The PR takes care of it, fwiw.

**Comment by EricZimmerman** [comment]
its that way intentionally, so that people cant do SOFTWARE\* and get a billion things out for no reason.

**Comment by EricZimmerman** [comment]
i reopened because i hadnt pulled it in yet.

**Comment by EricZimmerman** [comment]
i am happy to look at this again tho if it looks like its a bug

**Pull request merged**
