### PR TITLE
Add UserClassesASEPs.rep and add LocalServer32 to SoftwareClassesASEPs

### PR DESCRIPTION
**Pull request by Karneades**
## Description

This UserClassesASEPs rep file reads the classes keys for UsrClass.dat which are currently missing using other rep files. Furthermore, this commit adds support for LocalServer32 in SoftwareClassesASEPs.rep to also read that key. This rep file can be used for among others to analyse com hijacking.

## Checklist:
Please replace every instance of `[ ]` with `[X]`

- [x] I have generated a unique GUID for my Batch file(s)
- [x] I have tested and validated the new Batch file(s) work with my test data and achieve the desired output
- [x] I have placed the Batch file(s) within the .\RECmd\BatchExamples directory
- [x] I have set or updated the version of my Batch file(s)
- [ ] I have made an attempt to document the artifacts within the Batch file(s)
  -  Comment: same artifacts as with software hive now just adding support for usrclass

Thank you for your submission and for contributing to the DFIR community!

### CODE REVIEW

**Comment by rathbuna** [comment]
@Karneades please review the failed check above, i.e. too many spaces after a colon. Fix and recommit, at your leisure.

**Comment by rathbuna** [comment]
One last thing. I noticed you have {*} instead of * in KeyPath: Classes\CLSID\{*}\LocalServer32. Did you confirm that works the same as *? I am asking mostly because I've only ever used * so I didn't know if that was also acceptable syntax to use the brackets.

**Comment by Karneades** [comment]
I c&p from the existing SoftwareClassesASEPs. Not sure what the difference is.

**Comment by rathbuna** [comment]
Ah interesting. Alright, well if Lint doesn't hit on it then it should be all the same! I've not dove into the ASEPs yet but that's forthcoming. There's a lot in there, as you can see.

**Comment by Karneades** [comment]
Thanks for merging. KAPE file is also comming shortly.

**Pull request merged**
